# Generated by Django 3.2.6 on 2021-11-04 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20210211_2106'),
        ('flights', '0003_passenger'),
    ]

    operations = [
    ]
